// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laeupgwngrunaaxvkokf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZXVwZ3duZ3J1bmFheHZrb2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDUwODMsImV4cCI6MjA1NTIyMTA4M30.p5vE9xpsbDaF-4UFSfI_mI6mBoDygGVMDZkOKafMUXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);